itlized_social_endpoint:
    path:  /social/auth
    defaults: { _controller: ItlizedSocialBundle:Social:auth }
itlized_social_connect:
    path:  /social/connect/{provider}
    defaults: { _controller: ItlizedSocialBundle:Social:connect }
